# Main Window
TITLE = "OpenGS - Map Tool"
WINDOW_SIZE_WIDTH = 1100
WINDOW_SIZE_HEIGHT = 950
VERSION = "0.2"

# Land Province slider
LAND_PROVINCES_MIN = 100
LAND_PROVINCES_MAX = 100000
LAND_PROVINCES_DEFAULT = 3000
LAND_PROVINCES_TICK = 200
LAND_PROVINCES_STEP = 100

# Ocean Province slider
OCEAN_PROVINCES_MIN = 10
OCEAN_PROVINCES_MAX = 10000
OCEAN_PROVINCES_DEFAULT = 300
OCEAN_PROVINCES_TICK = 20
OCEAN_PROVINCES_STEP = 10

# Land Territory slider
LAND_TERRITORIES_MIN = 100
LAND_TERRITORIES_MAX = 10000
LAND_TERRITORIES_DEFAULT = 3000
LAND_TERRITORIES_TICK = 200
LAND_TERRITORIES_STEP = 100

# Ocean Territory slider
OCEAN_TERRITORIES_MIN = 10
OCEAN_TERRITORIES_MAX = 1000
OCEAN_TERRITORIES_DEFAULT = 300
OCEAN_TERRITORIES_TICK = 20
OCEAN_TERRITORIES_STEP = 10

# Land Map Color Code
OCEAN_COLOR = (5, 20, 18)  # RGB

# Boundary Map Color Code
BOUNDARY_COLOR = (0, 0, 0)

# Image Display
MAX_IMAGE_PIXELS = 300000000
DISPLAY_SIZE_WIDTH = 1050
DISPLAY_SIZE_HEIGHT = 900

# Number Series
PROVINCE_ID_PREFIX = "prv-"
PROVINCE_ID_START = 1
PROVINCE_ID_END = 999999
TERRITORY_ID_PREFIX = "ter-"
TERRITORY_ID_START = 1
TERRITORY_ID_END = 999999
